### ISSUE TITLE
Colors are mis-compiling

### ISSUE THREAD

**Issue by shaneholloman** [shoestrap/shoestrap-3#614]
Basically style compiling is broken

`#40b740` **Green** is compiling as `#4400bb` **purple**
**Black** is compiling as **white** for the input fields

There's probably more misfiring, I just wanted to tell you fast as possible so we can fix this ASAP

**Comment by s3w47m88** [comment]
I'm experiencing this as well.

**Comment by fovoc** [comment]
Hey there all,
I was just going backwards in master branch trying to get a working state of the compiling procedure. 
I believe that it's this commit -> https://github.com/shoestrap/shoestrap-3/commit/387ceffd3320581924197d8d184b6aba640dca78 that things seems to work as should have.
Can you verify that compiling calculations are working in this state? I'll try to get this done in a seperate branch before committing into the master and release a new version.
Thanks for all the feedback here in advance and I'm sorry for any frustration.

Cheers,
Dimitris
